// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.api.model;

import java.io.Serializable;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Experimental;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Immutable;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.NotThreadSafe;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.ThreadSafe;

/**
 * This is the file specification used to activate the profile. The {@code missing} value
 * is the location of a file that needs to exist, and if it doesn't, the profile will be
 * activated. On the other hand, {@code exists} will test for the existence of the file and if it is
 * there, the profile will be activated.
 * <p>Variable interpolation for these file specifications is limited to {@code ${project.basedir}},
 * system properties and user properties.</p>
 */
@Experimental
@Generated @ThreadSafe @Immutable
public class ActivationFile
    implements Serializable, InputLocationTracker
{
    /**
     * The name of the file that must be missing to activate the profile. Please note, that missing and exists
     * fields cannot be used together. Only one of them should be used at any one time.
     */
    final String missing;
    /**
     * The name of the file that must exist to activate the profile. Please note, that missing and exists
     * fields cannot be used together. Only one of them should be used at any one time.
     */
    final String exists;
    /** Locations */
    final Map<Object, InputLocation> locations;
    /** Location tracking */
    final InputLocation importedFrom;

    /**
      * Constructor for this class, to be called from its subclasses and {@link Builder}.
      * @see Builder#build()
      */
    protected ActivationFile(Builder builder) {
        this.missing = builder.missing != null ? builder.missing : (builder.base != null ? builder.base.missing : null);
        this.exists = builder.exists != null ? builder.exists : (builder.base != null ? builder.base.exists : null);
        this.locations = builder.computeLocations();
        this.importedFrom = builder.importedFrom;
    }

    /**
     * The name of the file that must be missing to activate the profile. Please note, that missing and exists
     * fields cannot be used together. Only one of them should be used at any one time.
     *
     * @return a {@code String}
     */
    public String getMissing() {
        return this.missing;
    }

    /**
     * The name of the file that must exist to activate the profile. Please note, that missing and exists
     * fields cannot be used together. Only one of them should be used at any one time.
     *
     * @return a {@code String}
     */
    public String getExists() {
        return this.exists;
    }

    /**
     * Gets the location of the specified field in the input source.
     *
     * @param key the key of the field, must not be {@code null}
     * @return the location of the field in the input source or {@code null} if unknown
     * @throws NullPointerException if {@code key} is {@code null}
     */
    public InputLocation getLocation(Object key) {
        Objects.requireNonNull(key, "key");
        return locations.get(key);
    }

    /**
     * Gets the keys of the locations of the input source.
     */
    public Set<Object> getLocationKeys() {
        return locations.keySet();
    }

    protected Stream<Object> getLocationKeyStream() {
        return locations.keySet().stream();
    }

    /**
     * Gets the input location that caused this model to be read.
     */
    public InputLocation getImportedFrom() {
        return importedFrom;
    }

    /**
     * Creates a new builder with this object as the basis.
     *
     * @return a {@code Builder}
     */
    @Nonnull
    public Builder with() {
        return newBuilder(this);
    }
    /**
     * Creates a new {@code ActivationFile} instance using the specified missing.
     *
     * @param missing the new {@code String} to use
     * @return a {@code ActivationFile} with the specified missing
     */
    @Nonnull
    public ActivationFile withMissing(String missing) {
        return newBuilder(this, true).missing(missing).build();
    }
    /**
     * Creates a new {@code ActivationFile} instance using the specified exists.
     *
     * @param exists the new {@code String} to use
     * @return a {@code ActivationFile} with the specified exists
     */
    @Nonnull
    public ActivationFile withExists(String exists) {
        return newBuilder(this, true).exists(exists).build();
    }

    /**
     * Creates a new {@code ActivationFile} instance.
     * Equivalent to {@code newInstance(true)}.
     * @see #newInstance(boolean)
     *
     * @return a new {@code ActivationFile}
     */
    @Nonnull
    public static ActivationFile newInstance() {
        return newInstance(true);
    }

    /**
     * Creates a new {@code ActivationFile} instance using default values or not.
     * Equivalent to {@code newBuilder(withDefaults).build()}.
     *
     * @param withDefaults the boolean indicating whether default values should be used
     * @return a new {@code ActivationFile}
     */
    @Nonnull
    public static ActivationFile newInstance(boolean withDefaults) {
        return newBuilder(withDefaults).build();
    }

    /**
     * Creates a new {@code ActivationFile} builder instance.
     * Equivalent to {@code newBuilder(true)}.
     * @see #newBuilder(boolean)
     *
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder() {
        return newBuilder(true);
    }

    /**
     * Creates a new {@code ActivationFile} builder instance using default values or not.
     *
     * @param withDefaults the boolean indicating whether default values should be used
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder(boolean withDefaults) {
        return new Builder(withDefaults);
    }

    /**
     * Creates a new {@code ActivationFile} builder instance using the specified object as a basis.
     * Equivalent to {@code newBuilder(from, false)}.
     *
     * @param from the {@code ActivationFile} instance to use as a basis
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder(ActivationFile from) {
        return newBuilder(from, false);
    }

    /**
     * Creates a new {@code ActivationFile} builder instance using the specified object as a basis.
     *
     * @param from the {@code ActivationFile} instance to use as a basis
     * @param forceCopy the boolean indicating if a copy should be forced
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder(ActivationFile from, boolean forceCopy) {
        return new Builder(from, forceCopy);
    }

    /**
     * Builder class used to create ActivationFile instances.
     * @see #with()
     * @see #newBuilder()
     */
    @NotThreadSafe
    public static class Builder
    {
        ActivationFile base;
        String missing;
        String exists;
        Map<Object, InputLocation> locations;
        InputLocation importedFrom;

        protected Builder(boolean withDefaults) {
            if (withDefaults) {
            }
        }

        protected Builder(ActivationFile base, boolean forceCopy) {
            if (forceCopy) {
                this.missing = base.missing;
                this.exists = base.exists;
                this.locations = base.locations;
                this.importedFrom = base.importedFrom;
            } else {
                this.base = base;
            }
        }

        @Nonnull
        public Builder missing(String missing) {
            this.missing = missing;
            return this;
        }

        @Nonnull
        public Builder exists(String exists) {
            this.exists = exists;
            return this;
        }


        @Nonnull
        public Builder location(Object key, InputLocation location) {
            if (location != null) {
                if (!(this.locations instanceof HashMap)) {
                    this.locations = this.locations != null ? new HashMap<>(this.locations) : new HashMap<>();
                }
                this.locations.put(key, location);
            }
            return this;
        }

        @Nonnull
        public Builder importedFrom(InputLocation importedFrom) {
            this.importedFrom = importedFrom;
            return this;
        }

        @Nonnull
        public ActivationFile build() {
            // this method should not contain any logic other than creating (or reusing) an object in order to ease subclassing
            if (base != null
                    && (missing == null || missing == base.missing)
                    && (exists == null || exists == base.exists)
            ) {
                return base;
            }
            return new ActivationFile(this);
        }

        Map<Object, InputLocation> computeLocations() {
            Map<Object, InputLocation> newlocs = locations != null ? locations : Map.of();
            Map<Object, InputLocation> oldlocs = base != null ? base.locations : Map.of();
            if (newlocs.isEmpty()) {
                return Map.copyOf(oldlocs);
            }
            if (oldlocs.isEmpty()) {
                return Map.copyOf(newlocs);
            }
            return Stream.concat(newlocs.entrySet().stream(), oldlocs.entrySet().stream())
                    // Keep value from newlocs in case of duplicates
                    .collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, Map.Entry::getValue, (v1, v2) -> v1));
        }
    }

}
