// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.api.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Experimental;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Immutable;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.NotThreadSafe;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.ThreadSafe;

/**
 * A PatternSet for files.
 */
@Experimental
@Generated @ThreadSafe @Immutable
public class FileSet
    extends PatternSet
    implements Serializable, InputLocationTracker
{
    /**
     * Describe the directory where the resources are stored. The path is relative
     * to the POM.
     */
    final String directory;

    /**
      * Constructor for this class, to be called from its subclasses and {@link Builder}.
      * @see Builder#build()
      */
    protected FileSet(Builder builder) {
        super(builder);
        this.directory = builder.directory != null ? builder.directory : (builder.base != null ? builder.base.directory : null);
    }

    /**
     * Describe the directory where the resources are stored. The path is relative
     * to the POM.
     *
     * @return a {@code String}
     */
    public String getDirectory() {
        return this.directory;
    }

    /**
     * Creates a new builder with this object as the basis.
     *
     * @return a {@code Builder}
     */
    @Nonnull
    public Builder with() {
        return newBuilder(this);
    }
    /**
     * Creates a new {@code FileSet} instance using the specified includes.
     *
     * @param includes the new {@code Collection<String>} to use
     * @return a {@code FileSet} with the specified includes
     */
    @Nonnull
    public FileSet withIncludes(Collection<String> includes) {
        return newBuilder(this, true).includes(includes).build();
    }
    /**
     * Creates a new {@code FileSet} instance using the specified excludes.
     *
     * @param excludes the new {@code Collection<String>} to use
     * @return a {@code FileSet} with the specified excludes
     */
    @Nonnull
    public FileSet withExcludes(Collection<String> excludes) {
        return newBuilder(this, true).excludes(excludes).build();
    }
    /**
     * Creates a new {@code FileSet} instance using the specified directory.
     *
     * @param directory the new {@code String} to use
     * @return a {@code FileSet} with the specified directory
     */
    @Nonnull
    public FileSet withDirectory(String directory) {
        return newBuilder(this, true).directory(directory).build();
    }

    /**
     * Creates a new {@code FileSet} instance.
     * Equivalent to {@code newInstance(true)}.
     * @see #newInstance(boolean)
     *
     * @return a new {@code FileSet}
     */
    @Nonnull
    public static FileSet newInstance() {
        return newInstance(true);
    }

    /**
     * Creates a new {@code FileSet} instance using default values or not.
     * Equivalent to {@code newBuilder(withDefaults).build()}.
     *
     * @param withDefaults the boolean indicating whether default values should be used
     * @return a new {@code FileSet}
     */
    @Nonnull
    public static FileSet newInstance(boolean withDefaults) {
        return newBuilder(withDefaults).build();
    }

    /**
     * Creates a new {@code FileSet} builder instance.
     * Equivalent to {@code newBuilder(true)}.
     * @see #newBuilder(boolean)
     *
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder() {
        return newBuilder(true);
    }

    /**
     * Creates a new {@code FileSet} builder instance using default values or not.
     *
     * @param withDefaults the boolean indicating whether default values should be used
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder(boolean withDefaults) {
        return new Builder(withDefaults);
    }

    /**
     * Creates a new {@code FileSet} builder instance using the specified object as a basis.
     * Equivalent to {@code newBuilder(from, false)}.
     *
     * @param from the {@code FileSet} instance to use as a basis
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder(FileSet from) {
        return newBuilder(from, false);
    }

    /**
     * Creates a new {@code FileSet} builder instance using the specified object as a basis.
     *
     * @param from the {@code FileSet} instance to use as a basis
     * @param forceCopy the boolean indicating if a copy should be forced
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder(FileSet from, boolean forceCopy) {
        return new Builder(from, forceCopy);
    }

    /**
     * Builder class used to create FileSet instances.
     * @see #with()
     * @see #newBuilder()
     */
    @NotThreadSafe
    public static class Builder
        extends PatternSet.Builder
    {
        FileSet base;
        String directory;

        protected Builder(boolean withDefaults) {
            super(withDefaults);
            if (withDefaults) {
            }
        }

        protected Builder(FileSet base, boolean forceCopy) {
            super(base, forceCopy);
            if (forceCopy) {
                this.directory = base.directory;
                this.locations = base.locations;
                this.importedFrom = base.importedFrom;
            } else {
                this.base = base;
            }
        }

        @Nonnull
        public Builder includes(Collection<String> includes) {
            this.includes = includes;
            return this;
        }

        @Nonnull
        public Builder excludes(Collection<String> excludes) {
            this.excludes = excludes;
            return this;
        }

        @Nonnull
        public Builder directory(String directory) {
            this.directory = directory;
            return this;
        }


        @Nonnull
        public Builder location(Object key, InputLocation location) {
            if (location != null) {
                if (!(this.locations instanceof HashMap)) {
                    this.locations = this.locations != null ? new HashMap<>(this.locations) : new HashMap<>();
                }
                this.locations.put(key, location);
            }
            return this;
        }

        @Nonnull
        public Builder importedFrom(InputLocation importedFrom) {
            this.importedFrom = importedFrom;
            return this;
        }

        @Nonnull
        public FileSet build() {
            // this method should not contain any logic other than creating (or reusing) an object in order to ease subclassing
            if (base != null
                    && (includes == null || includes == base.includes)
                    && (excludes == null || excludes == base.excludes)
                    && (directory == null || directory == base.directory)
            ) {
                return base;
            }
            return new FileSet(this);
        }

    }



    /**
     * @see java.lang.Object#toString()
     */
    public String toString() {
        return "FileSet {directory: " + getDirectory() + ", " + super.toString() + "}";
    }


}
