// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.api.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Experimental;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Immutable;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.NotThreadSafe;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.ThreadSafe;

/**
 * This element describes all of the classpath resources associated with a project
 * or unit tests.
 *
 * @deprecated Replaced by {@code <Source>} with {@code resources} language.
 */
@Deprecated(since = "4.0.0")
@Experimental
@Generated @ThreadSafe @Immutable
public class Resource
    extends FileSet
    implements Serializable, InputLocationTracker
{
    /**
     * Describe the resource target path. The path is relative to the target/classes
     * directory (i.e. {@code ${project.build.outputDirectory}}).
     * For example, if you want that resource to appear in a specific package
     * ({@code com.netflix.tools.jig.internal.org.apache.maven.messages}), you must specify this
     * element with this value: {@code org/apache/maven/messages}.
     * This is not required if you simply put the resources in that directory
     * structure at the source, however.
     */
    final String targetPath;
    /**
     * Whether resources are filtered to replace tokens with parameterised values or not.
     * The values are taken from the {@code properties} element and from the
     * properties in the files listed in the {@code filters} element. Note: While the type
     * of this field is {@code String} for technical reasons, the semantic type is actually
     * {@code Boolean}. Default value is {@code false}.
     */
    final String filtering;

    /**
      * Constructor for this class, to be called from its subclasses and {@link Builder}.
      * @see Builder#build()
      */
    protected Resource(Builder builder) {
        super(builder);
        this.targetPath = builder.targetPath != null ? builder.targetPath : (builder.base != null ? builder.base.targetPath : null);
        this.filtering = builder.filtering != null ? builder.filtering : (builder.base != null ? builder.base.filtering : null);
    }

    /**
     * Describe the resource target path. The path is relative to the target/classes
     * directory (i.e. {@code ${project.build.outputDirectory}}).
     * For example, if you want that resource to appear in a specific package
     * ({@code com.netflix.tools.jig.internal.org.apache.maven.messages}), you must specify this
     * element with this value: {@code org/apache/maven/messages}.
     * This is not required if you simply put the resources in that directory
     * structure at the source, however.
     *
     * @return a {@code String}
     */
    public String getTargetPath() {
        return this.targetPath;
    }

    /**
     * Whether resources are filtered to replace tokens with parameterised values or not.
     * The values are taken from the {@code properties} element and from the
     * properties in the files listed in the {@code filters} element. Note: While the type
     * of this field is {@code String} for technical reasons, the semantic type is actually
     * {@code Boolean}. Default value is {@code false}.
     *
     * @return a {@code String}
     */
    public String getFiltering() {
        return this.filtering;
    }

    /**
     * Creates a new builder with this object as the basis.
     *
     * @return a {@code Builder}
     */
    @Nonnull
    public Builder with() {
        return newBuilder(this);
    }
    /**
     * Creates a new {@code Resource} instance using the specified includes.
     *
     * @param includes the new {@code Collection<String>} to use
     * @return a {@code Resource} with the specified includes
     */
    @Nonnull
    public Resource withIncludes(Collection<String> includes) {
        return newBuilder(this, true).includes(includes).build();
    }
    /**
     * Creates a new {@code Resource} instance using the specified excludes.
     *
     * @param excludes the new {@code Collection<String>} to use
     * @return a {@code Resource} with the specified excludes
     */
    @Nonnull
    public Resource withExcludes(Collection<String> excludes) {
        return newBuilder(this, true).excludes(excludes).build();
    }
    /**
     * Creates a new {@code Resource} instance using the specified directory.
     *
     * @param directory the new {@code String} to use
     * @return a {@code Resource} with the specified directory
     */
    @Nonnull
    public Resource withDirectory(String directory) {
        return newBuilder(this, true).directory(directory).build();
    }
    /**
     * Creates a new {@code Resource} instance using the specified targetPath.
     *
     * @param targetPath the new {@code String} to use
     * @return a {@code Resource} with the specified targetPath
     */
    @Nonnull
    public Resource withTargetPath(String targetPath) {
        return newBuilder(this, true).targetPath(targetPath).build();
    }
    /**
     * Creates a new {@code Resource} instance using the specified filtering.
     *
     * @param filtering the new {@code String} to use
     * @return a {@code Resource} with the specified filtering
     */
    @Nonnull
    public Resource withFiltering(String filtering) {
        return newBuilder(this, true).filtering(filtering).build();
    }

    /**
     * Creates a new {@code Resource} instance.
     * Equivalent to {@code newInstance(true)}.
     * @see #newInstance(boolean)
     *
     * @return a new {@code Resource}
     */
    @Nonnull
    public static Resource newInstance() {
        return newInstance(true);
    }

    /**
     * Creates a new {@code Resource} instance using default values or not.
     * Equivalent to {@code newBuilder(withDefaults).build()}.
     *
     * @param withDefaults the boolean indicating whether default values should be used
     * @return a new {@code Resource}
     */
    @Nonnull
    public static Resource newInstance(boolean withDefaults) {
        return newBuilder(withDefaults).build();
    }

    /**
     * Creates a new {@code Resource} builder instance.
     * Equivalent to {@code newBuilder(true)}.
     * @see #newBuilder(boolean)
     *
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder() {
        return newBuilder(true);
    }

    /**
     * Creates a new {@code Resource} builder instance using default values or not.
     *
     * @param withDefaults the boolean indicating whether default values should be used
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder(boolean withDefaults) {
        return new Builder(withDefaults);
    }

    /**
     * Creates a new {@code Resource} builder instance using the specified object as a basis.
     * Equivalent to {@code newBuilder(from, false)}.
     *
     * @param from the {@code Resource} instance to use as a basis
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder(Resource from) {
        return newBuilder(from, false);
    }

    /**
     * Creates a new {@code Resource} builder instance using the specified object as a basis.
     *
     * @param from the {@code Resource} instance to use as a basis
     * @param forceCopy the boolean indicating if a copy should be forced
     * @return a new {@code Builder}
     */
    @Nonnull
    public static Builder newBuilder(Resource from, boolean forceCopy) {
        return new Builder(from, forceCopy);
    }

    /**
     * Builder class used to create Resource instances.
     * @see #with()
     * @see #newBuilder()
     */
    @NotThreadSafe
    public static class Builder
        extends FileSet.Builder
    {
        Resource base;
        String targetPath;
        String filtering;

        protected Builder(boolean withDefaults) {
            super(withDefaults);
            if (withDefaults) {
            }
        }

        protected Builder(Resource base, boolean forceCopy) {
            super(base, forceCopy);
            if (forceCopy) {
                this.targetPath = base.targetPath;
                this.filtering = base.filtering;
                this.locations = base.locations;
                this.importedFrom = base.importedFrom;
            } else {
                this.base = base;
            }
        }

        @Nonnull
        public Builder includes(Collection<String> includes) {
            this.includes = includes;
            return this;
        }

        @Nonnull
        public Builder excludes(Collection<String> excludes) {
            this.excludes = excludes;
            return this;
        }

        @Nonnull
        public Builder directory(String directory) {
            this.directory = directory;
            return this;
        }

        @Nonnull
        public Builder targetPath(String targetPath) {
            this.targetPath = targetPath;
            return this;
        }

        @Nonnull
        public Builder filtering(String filtering) {
            this.filtering = filtering;
            return this;
        }


        @Nonnull
        public Builder location(Object key, InputLocation location) {
            if (location != null) {
                if (!(this.locations instanceof HashMap)) {
                    this.locations = this.locations != null ? new HashMap<>(this.locations) : new HashMap<>();
                }
                this.locations.put(key, location);
            }
            return this;
        }

        @Nonnull
        public Builder importedFrom(InputLocation importedFrom) {
            this.importedFrom = importedFrom;
            return this;
        }

        @Nonnull
        public Resource build() {
            // this method should not contain any logic other than creating (or reusing) an object in order to ease subclassing
            if (base != null
                    && (includes == null || includes == base.includes)
                    && (excludes == null || excludes == base.excludes)
                    && (directory == null || directory == base.directory)
                    && (targetPath == null || targetPath == base.targetPath)
                    && (filtering == null || filtering == base.filtering)
            ) {
                return base;
            }
            return new Resource(this);
        }

    }



    /**
     * @deprecated this was unused and has no replacement, this method returns {@code null} now.
     */
    @Deprecated(since = "4.0.0")
    public String getMergeId() {
        return null;
    }

    /**
     * @deprecated this was unused and has no replacement, this method is a no-op now.
     */
    @Deprecated(since = "4.0.0")
    public void setMergeId(String mergeId) {
    }




    public boolean isFiltering() {
        return (getFiltering() != null) ? Boolean.parseBoolean(getFiltering()) : false;
    }




    /**
     * @see java.lang.Object#toString()
     */
    public String toString() {
        return "Resource {targetPath: " + getTargetPath() + ", filtering: " + isFiltering() + ", " + super.toString() + "}";
    }


}
