/*
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 2.6.0,
 any modifications will be overwritten.
 ==============================================================
 */

package com.netflix.tools.jig.internal.org.apache.maven.settings;

/**
 *
 *         Repository contains the information needed for
 * establishing
 *         connections with remote repository
 *       .
 *
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Repository
    extends RepositoryBase
    implements java.io.Serializable, java.lang.Cloneable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     *
     *             How to handle downloading of releases from this
     * repository
     *           .
     */
    private RepositoryPolicy releases;

    /**
     *
     *             How to handle downloading of snapshots from this
     * repository
     *           .
     */
    private RepositoryPolicy snapshots;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method clone.
     *
     * @return Repository
     */
    public Repository clone()
    {
        try
        {
            Repository copy = (Repository) super.clone();

            if ( this.releases != null )
            {
                copy.releases = (RepositoryPolicy) this.releases.clone();
            }

            if ( this.snapshots != null )
            {
                copy.snapshots = (RepositoryPolicy) this.snapshots.clone();
            }

            return copy;
        }
        catch ( java.lang.Exception ex )
        {
            throw (java.lang.RuntimeException) new java.lang.UnsupportedOperationException( getClass().getName()
                + " does not support clone()" ).initCause( ex );
        }
    } //-- Repository clone()

    /**
     * Get how to handle downloading of releases from this
     * repository.
     *
     * @return RepositoryPolicy
     */
    public RepositoryPolicy getReleases()
    {
        return this.releases;
    } //-- RepositoryPolicy getReleases()

    /**
     * Get how to handle downloading of snapshots from this
     * repository.
     *
     * @return RepositoryPolicy
     */
    public RepositoryPolicy getSnapshots()
    {
        return this.snapshots;
    } //-- RepositoryPolicy getSnapshots()

    /**
     * Set how to handle downloading of releases from this
     * repository.
     *
     * @param releases a releases object.
     */
    public void setReleases( RepositoryPolicy releases )
    {
        this.releases = releases;
    } //-- void setReleases( RepositoryPolicy )

    /**
     * Set how to handle downloading of snapshots from this
     * repository.
     *
     * @param snapshots a snapshots object.
     */
    public void setSnapshots( RepositoryPolicy snapshots )
    {
        this.snapshots = snapshots;
    } //-- void setSnapshots( RepositoryPolicy )



    /**
     * @see com.netflix.tools.jig.internal.org.apache.maven.settings.RepositoryBase#equals(java.lang.Object)
     */
    public boolean equals( Object obj )
    {
        return super.equals( obj );
    }


}
