// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.model;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class ActivationProperty
    extends BaseObject
{

    public ActivationProperty() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.model.ActivationProperty.newInstance());
    }

    public ActivationProperty(com.netflix.tools.jig.internal.org.apache.maven.api.model.ActivationProperty delegate) {
        this(delegate, null);
    }

    public ActivationProperty(com.netflix.tools.jig.internal.org.apache.maven.api.model.ActivationProperty delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public ActivationProperty clone(){
        return new ActivationProperty(getDelegate());
    }

    public com.netflix.tools.jig.internal.org.apache.maven.api.model.ActivationProperty getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.model.ActivationProperty) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof ActivationProperty)) {
            return false;
        }
        ActivationProperty that = (ActivationProperty) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    public String getName() {
        return getDelegate().getName();
    }

    public void setName(String name) {
        if (!Objects.equals(name, getName())) {
            update(getDelegate().withName(name));
        }
    }

    public String getValue() {
        return getDelegate().getValue();
    }

    public void setValue(String value) {
        if (!Objects.equals(value, getValue())) {
            update(getDelegate().withValue(value));
        }
    }

    public InputLocation getLocation(Object key) {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getLocation(key);
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setLocation(Object key, InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.ActivationProperty.newBuilder(getDelegate(), true)
                        .location(key, location != null ? location.toApiLocation() : null).build());
    }

    public InputLocation getImportedFrom() {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getImportedFrom();
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setImportedFrom(InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.ActivationProperty.newBuilder(getDelegate(), true)
                        .importedFrom(location != null ? location.toApiLocation() : null).build());
    }

    public Set<Object> getLocationKeys() {
        return getDelegate().getLocationKeys();
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.model.ActivationProperty> activationPropertyToApiV4(List<ActivationProperty> list) {
        return list != null ? new WrapperList<>(list, ActivationProperty::getDelegate, ActivationProperty::new) : null;
    }

    public static List<ActivationProperty> activationPropertyToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.model.ActivationProperty> list) {
        return list != null ? new WrapperList<>(list, ActivationProperty::new, ActivationProperty::getDelegate) : null;
    }

}
