// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.model;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class CiManagement
    extends BaseObject
{

    public CiManagement() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.model.CiManagement.newInstance());
    }

    public CiManagement(com.netflix.tools.jig.internal.org.apache.maven.api.model.CiManagement delegate) {
        this(delegate, null);
    }

    public CiManagement(com.netflix.tools.jig.internal.org.apache.maven.api.model.CiManagement delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public CiManagement clone(){
        return new CiManagement(getDelegate());
    }

    public com.netflix.tools.jig.internal.org.apache.maven.api.model.CiManagement getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.model.CiManagement) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof CiManagement)) {
            return false;
        }
        CiManagement that = (CiManagement) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    public String getSystem() {
        return getDelegate().getSystem();
    }

    public void setSystem(String system) {
        if (!Objects.equals(system, getSystem())) {
            update(getDelegate().withSystem(system));
        }
    }

    public String getUrl() {
        return getDelegate().getUrl();
    }

    public void setUrl(String url) {
        if (!Objects.equals(url, getUrl())) {
            update(getDelegate().withUrl(url));
        }
    }

    @Nonnull
    public List<Notifier> getNotifiers() {
        return new WrapperList<Notifier, com.netflix.tools.jig.internal.org.apache.maven.api.model.Notifier>(
                    () -> getDelegate().getNotifiers(), l -> update(getDelegate().withNotifiers(l)),
                    d -> new Notifier(d, this), Notifier::getDelegate);
    }

    public void setNotifiers(List<Notifier> notifiers) {
        if (notifiers == null) {
            notifiers = Collections.emptyList();
        }
        if (!Objects.equals(notifiers, getNotifiers())) {
            update(getDelegate().withNotifiers(
                notifiers.stream().map(c -> c.getDelegate()).collect(Collectors.toList())));
            notifiers.forEach(e -> e.childrenTracking = this::replace);
        }
    }

    public void addNotifier(Notifier notifier) {
        update(getDelegate().withNotifiers(
               Stream.concat(getDelegate().getNotifiers().stream(), Stream.of(notifier.getDelegate()))
                        .collect(Collectors.toList())));
        notifier.childrenTracking = this::replace;
    }

    public void removeNotifier(Notifier notifier) {
        update(getDelegate().withNotifiers(
               getDelegate().getNotifiers().stream()
                        .filter(e -> !Objects.equals(e, notifier))
                        .collect(Collectors.toList())));
        notifier.childrenTracking = null;
    }

    public InputLocation getLocation(Object key) {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getLocation(key);
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setLocation(Object key, InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.CiManagement.newBuilder(getDelegate(), true)
                        .location(key, location != null ? location.toApiLocation() : null).build());
    }

    public InputLocation getImportedFrom() {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getImportedFrom();
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setImportedFrom(InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.CiManagement.newBuilder(getDelegate(), true)
                        .importedFrom(location != null ? location.toApiLocation() : null).build());
    }

    public Set<Object> getLocationKeys() {
        return getDelegate().getLocationKeys();
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        if (getDelegate().getNotifiers().contains(oldDelegate)) {
            List<com.netflix.tools.jig.internal.org.apache.maven.api.model.Notifier> list = new ArrayList<>(getDelegate().getNotifiers());
            list.replaceAll(d -> d == oldDelegate ? (com.netflix.tools.jig.internal.org.apache.maven.api.model.Notifier) newDelegate : d);
            update(getDelegate().withNotifiers(list));
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.model.CiManagement> ciManagementToApiV4(List<CiManagement> list) {
        return list != null ? new WrapperList<>(list, CiManagement::getDelegate, CiManagement::new) : null;
    }

    public static List<CiManagement> ciManagementToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.model.CiManagement> list) {
        return list != null ? new WrapperList<>(list, CiManagement::new, CiManagement::getDelegate) : null;
    }

}
