// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.model;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class DependencyManagement
    extends BaseObject
{

    public DependencyManagement() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.model.DependencyManagement.newInstance());
    }

    public DependencyManagement(com.netflix.tools.jig.internal.org.apache.maven.api.model.DependencyManagement delegate) {
        this(delegate, null);
    }

    public DependencyManagement(com.netflix.tools.jig.internal.org.apache.maven.api.model.DependencyManagement delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public DependencyManagement clone(){
        return new DependencyManagement(getDelegate());
    }

    public com.netflix.tools.jig.internal.org.apache.maven.api.model.DependencyManagement getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.model.DependencyManagement) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof DependencyManagement)) {
            return false;
        }
        DependencyManagement that = (DependencyManagement) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    @Nonnull
    public List<Dependency> getDependencies() {
        return new WrapperList<Dependency, com.netflix.tools.jig.internal.org.apache.maven.api.model.Dependency>(
                    () -> getDelegate().getDependencies(), l -> update(getDelegate().withDependencies(l)),
                    d -> new Dependency(d, this), Dependency::getDelegate);
    }

    public void setDependencies(List<Dependency> dependencies) {
        if (dependencies == null) {
            dependencies = Collections.emptyList();
        }
        if (!Objects.equals(dependencies, getDependencies())) {
            update(getDelegate().withDependencies(
                dependencies.stream().map(c -> c.getDelegate()).collect(Collectors.toList())));
            dependencies.forEach(e -> e.childrenTracking = this::replace);
        }
    }

    public void addDependency(Dependency dependency) {
        update(getDelegate().withDependencies(
               Stream.concat(getDelegate().getDependencies().stream(), Stream.of(dependency.getDelegate()))
                        .collect(Collectors.toList())));
        dependency.childrenTracking = this::replace;
    }

    public void removeDependency(Dependency dependency) {
        update(getDelegate().withDependencies(
               getDelegate().getDependencies().stream()
                        .filter(e -> !Objects.equals(e, dependency))
                        .collect(Collectors.toList())));
        dependency.childrenTracking = null;
    }

    public InputLocation getLocation(Object key) {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getLocation(key);
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setLocation(Object key, InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.DependencyManagement.newBuilder(getDelegate(), true)
                        .location(key, location != null ? location.toApiLocation() : null).build());
    }

    public InputLocation getImportedFrom() {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getImportedFrom();
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setImportedFrom(InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.DependencyManagement.newBuilder(getDelegate(), true)
                        .importedFrom(location != null ? location.toApiLocation() : null).build());
    }

    public Set<Object> getLocationKeys() {
        return getDelegate().getLocationKeys();
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        if (getDelegate().getDependencies().contains(oldDelegate)) {
            List<com.netflix.tools.jig.internal.org.apache.maven.api.model.Dependency> list = new ArrayList<>(getDelegate().getDependencies());
            list.replaceAll(d -> d == oldDelegate ? (com.netflix.tools.jig.internal.org.apache.maven.api.model.Dependency) newDelegate : d);
            update(getDelegate().withDependencies(list));
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.model.DependencyManagement> dependencyManagementToApiV4(List<DependencyManagement> list) {
        return list != null ? new WrapperList<>(list, DependencyManagement::getDelegate, DependencyManagement::new) : null;
    }

    public static List<DependencyManagement> dependencyManagementToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.model.DependencyManagement> list) {
        return list != null ? new WrapperList<>(list, DependencyManagement::new, DependencyManagement::getDelegate) : null;
    }

}
