// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.model;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class License
    extends BaseObject
{

    public License() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.model.License.newInstance());
    }

    public License(com.netflix.tools.jig.internal.org.apache.maven.api.model.License delegate) {
        this(delegate, null);
    }

    public License(com.netflix.tools.jig.internal.org.apache.maven.api.model.License delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public License clone(){
        return new License(getDelegate());
    }

    public com.netflix.tools.jig.internal.org.apache.maven.api.model.License getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.model.License) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof License)) {
            return false;
        }
        License that = (License) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    public String getName() {
        return getDelegate().getName();
    }

    public void setName(String name) {
        if (!Objects.equals(name, getName())) {
            update(getDelegate().withName(name));
        }
    }

    public String getUrl() {
        return getDelegate().getUrl();
    }

    public void setUrl(String url) {
        if (!Objects.equals(url, getUrl())) {
            update(getDelegate().withUrl(url));
        }
    }

    public String getDistribution() {
        return getDelegate().getDistribution();
    }

    public void setDistribution(String distribution) {
        if (!Objects.equals(distribution, getDistribution())) {
            update(getDelegate().withDistribution(distribution));
        }
    }

    public String getComments() {
        return getDelegate().getComments();
    }

    public void setComments(String comments) {
        if (!Objects.equals(comments, getComments())) {
            update(getDelegate().withComments(comments));
        }
    }

    public InputLocation getLocation(Object key) {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getLocation(key);
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setLocation(Object key, InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.License.newBuilder(getDelegate(), true)
                        .location(key, location != null ? location.toApiLocation() : null).build());
    }

    public InputLocation getImportedFrom() {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getImportedFrom();
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setImportedFrom(InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.License.newBuilder(getDelegate(), true)
                        .importedFrom(location != null ? location.toApiLocation() : null).build());
    }

    public Set<Object> getLocationKeys() {
        return getDelegate().getLocationKeys();
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.model.License> licenseToApiV4(List<License> list) {
        return list != null ? new WrapperList<>(list, License::getDelegate, License::new) : null;
    }

    public static List<License> licenseToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.model.License> list) {
        return list != null ? new WrapperList<>(list, License::new, License::getDelegate) : null;
    }



    /**
     * @see java.lang.Object#toString()
     */
    public String toString()
    {
        return "License {name=" + getName() + ", url=" + getUrl() + "}";
    }


}
