// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.model;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class PatternSet
    extends BaseObject
{

    public PatternSet() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.model.PatternSet.newInstance());
    }

    public PatternSet(com.netflix.tools.jig.internal.org.apache.maven.api.model.PatternSet delegate) {
        this(delegate, null);
    }

    public PatternSet(com.netflix.tools.jig.internal.org.apache.maven.api.model.PatternSet delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public PatternSet clone(){
        return new PatternSet(getDelegate());
    }

    public com.netflix.tools.jig.internal.org.apache.maven.api.model.PatternSet getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.model.PatternSet) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof PatternSet)) {
            return false;
        }
        PatternSet that = (PatternSet) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    @Nonnull
    public List<String> getIncludes() {
        return new WrapperList<String, String>(() -> getDelegate().getIncludes(), this::setIncludes, s -> s, s -> s);
    }

    public void setIncludes(List<String> includes) {
        if (!Objects.equals(includes, getIncludes())) {
            update(getDelegate().withIncludes(includes));
        }
    }

    public void addInclude(String include) {
        update(getDelegate().withIncludes(
               Stream.concat(getDelegate().getIncludes().stream(), Stream.of(include))
                        .collect(Collectors.toList())));
    }

    public void removeInclude(String include) {
        update(getDelegate().withIncludes(
               getDelegate().getIncludes().stream()
                        .filter(e -> !Objects.equals(e, include))
                        .collect(Collectors.toList())));
    }

    @Nonnull
    public List<String> getExcludes() {
        return new WrapperList<String, String>(() -> getDelegate().getExcludes(), this::setExcludes, s -> s, s -> s);
    }

    public void setExcludes(List<String> excludes) {
        if (!Objects.equals(excludes, getExcludes())) {
            update(getDelegate().withExcludes(excludes));
        }
    }

    public void addExclude(String exclude) {
        update(getDelegate().withExcludes(
               Stream.concat(getDelegate().getExcludes().stream(), Stream.of(exclude))
                        .collect(Collectors.toList())));
    }

    public void removeExclude(String exclude) {
        update(getDelegate().withExcludes(
               getDelegate().getExcludes().stream()
                        .filter(e -> !Objects.equals(e, exclude))
                        .collect(Collectors.toList())));
    }

    public InputLocation getLocation(Object key) {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getLocation(key);
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setLocation(Object key, InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.PatternSet.newBuilder(getDelegate(), true)
                        .location(key, location != null ? location.toApiLocation() : null).build());
    }

    public InputLocation getImportedFrom() {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getImportedFrom();
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setImportedFrom(InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.PatternSet.newBuilder(getDelegate(), true)
                        .importedFrom(location != null ? location.toApiLocation() : null).build());
    }

    public Set<Object> getLocationKeys() {
        return getDelegate().getLocationKeys();
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.model.PatternSet> patternSetToApiV4(List<PatternSet> list) {
        return list != null ? new WrapperList<>(list, PatternSet::getDelegate, PatternSet::new) : null;
    }

    public static List<PatternSet> patternSetToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.model.PatternSet> list) {
        return list != null ? new WrapperList<>(list, PatternSet::new, PatternSet::getDelegate) : null;
    }



    /**
     * @see java.lang.Object#toString()
     */
    public String toString() {
        return "PatternSet [" +
            "includes: {" + getIncludes().stream().collect(java.util.stream.Collectors.joining(", ")) + "}, " +
            "excludes: {" + getExcludes().stream().collect(java.util.stream.Collectors.joining(", ")) + "}]";
    }


}
