// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.model;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class PluginManagement
    extends PluginContainer
    implements Serializable, Cloneable
{

    public PluginManagement() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginManagement.newInstance());
    }

    public PluginManagement(com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginManagement delegate) {
        this(delegate, null);
    }

    public PluginManagement(com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginManagement delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public PluginManagement clone(){
        return new PluginManagement(getDelegate());
    }

    @Override
    public com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginManagement getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginManagement) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof PluginManagement)) {
            return false;
        }
        PluginManagement that = (PluginManagement) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    public InputLocation getLocation(Object key) {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getLocation(key);
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setLocation(Object key, InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginManagement.newBuilder(getDelegate(), true)
                        .location(key, location != null ? location.toApiLocation() : null).build());
    }

    public InputLocation getImportedFrom() {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getImportedFrom();
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setImportedFrom(InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginManagement.newBuilder(getDelegate(), true)
                        .importedFrom(location != null ? location.toApiLocation() : null).build());
    }

    public Set<Object> getLocationKeys() {
        return getDelegate().getLocationKeys();
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginManagement> pluginManagementToApiV4(List<PluginManagement> list) {
        return list != null ? new WrapperList<>(list, PluginManagement::getDelegate, PluginManagement::new) : null;
    }

    public static List<PluginManagement> pluginManagementToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginManagement> list) {
        return list != null ? new WrapperList<>(list, PluginManagement::new, PluginManagement::getDelegate) : null;
    }

}
