// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.model;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;
import com.netflix.tools.jig.internal.org.codehaus.plexus.util.xml.Xpp3Dom;

@Generated
public class PluginExecution
    extends ConfigurationContainer
    implements Serializable, Cloneable
{

    public PluginExecution() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginExecution.newInstance());
    }

    public PluginExecution(com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginExecution delegate) {
        this(delegate, null);
    }

    public PluginExecution(com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginExecution delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public PluginExecution clone(){
        return new PluginExecution(getDelegate());
    }

    @Override
    public com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginExecution getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginExecution) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof PluginExecution)) {
            return false;
        }
        PluginExecution that = (PluginExecution) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    public String getId() {
        return getDelegate().getId();
    }

    public void setId(String id) {
        if (!Objects.equals(id, getId())) {
            update(getDelegate().withId(id));
        }
    }

    public String getPhase() {
        return getDelegate().getPhase();
    }

    public void setPhase(String phase) {
        if (!Objects.equals(phase, getPhase())) {
            update(getDelegate().withPhase(phase));
        }
    }

    public int getPriority() {
        return getDelegate().getPriority();
    }

    public void setPriority(int priority) {
        if (!Objects.equals(priority, getPriority())) {
            update(getDelegate().withPriority(priority));
        }
    }

    @Nonnull
    public List<String> getGoals() {
        return new WrapperList<String, String>(() -> getDelegate().getGoals(), this::setGoals, s -> s, s -> s);
    }

    public void setGoals(List<String> goals) {
        if (!Objects.equals(goals, getGoals())) {
            update(getDelegate().withGoals(goals));
        }
    }

    public void addGoal(String goal) {
        update(getDelegate().withGoals(
               Stream.concat(getDelegate().getGoals().stream(), Stream.of(goal))
                        .collect(Collectors.toList())));
    }

    public void removeGoal(String goal) {
        update(getDelegate().withGoals(
               getDelegate().getGoals().stream()
                        .filter(e -> !Objects.equals(e, goal))
                        .collect(Collectors.toList())));
    }

    public InputLocation getLocation(Object key) {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getLocation(key);
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setLocation(Object key, InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginExecution.newBuilder(getDelegate(), true)
                        .location(key, location != null ? location.toApiLocation() : null).build());
    }

    public InputLocation getImportedFrom() {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getImportedFrom();
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setImportedFrom(InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginExecution.newBuilder(getDelegate(), true)
                        .importedFrom(location != null ? location.toApiLocation() : null).build());
    }

    public Set<Object> getLocationKeys() {
        return getDelegate().getLocationKeys();
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginExecution> pluginExecutionToApiV4(List<PluginExecution> list) {
        return list != null ? new WrapperList<>(list, PluginExecution::getDelegate, PluginExecution::new) : null;
    }

    public static List<PluginExecution> pluginExecutionToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.model.PluginExecution> list) {
        return list != null ? new WrapperList<>(list, PluginExecution::new, PluginExecution::getDelegate) : null;
    }



    public static final String DEFAULT_EXECUTION_ID = "default";

    @Override
    public String toString() {
        return getId();
    }


}
