// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.model;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class Prerequisites
    extends BaseObject
{

    public Prerequisites() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.model.Prerequisites.newInstance());
    }

    public Prerequisites(com.netflix.tools.jig.internal.org.apache.maven.api.model.Prerequisites delegate) {
        this(delegate, null);
    }

    public Prerequisites(com.netflix.tools.jig.internal.org.apache.maven.api.model.Prerequisites delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public Prerequisites clone(){
        return new Prerequisites(getDelegate());
    }

    public com.netflix.tools.jig.internal.org.apache.maven.api.model.Prerequisites getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.model.Prerequisites) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof Prerequisites)) {
            return false;
        }
        Prerequisites that = (Prerequisites) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    public String getMaven() {
        return getDelegate().getMaven();
    }

    public void setMaven(String maven) {
        if (!Objects.equals(maven, getMaven())) {
            update(getDelegate().withMaven(maven));
        }
    }

    public InputLocation getLocation(Object key) {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getLocation(key);
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setLocation(Object key, InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.Prerequisites.newBuilder(getDelegate(), true)
                        .location(key, location != null ? location.toApiLocation() : null).build());
    }

    public InputLocation getImportedFrom() {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getImportedFrom();
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setImportedFrom(InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.Prerequisites.newBuilder(getDelegate(), true)
                        .importedFrom(location != null ? location.toApiLocation() : null).build());
    }

    public Set<Object> getLocationKeys() {
        return getDelegate().getLocationKeys();
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.model.Prerequisites> prerequisitesToApiV4(List<Prerequisites> list) {
        return list != null ? new WrapperList<>(list, Prerequisites::getDelegate, Prerequisites::new) : null;
    }

    public static List<Prerequisites> prerequisitesToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.model.Prerequisites> list) {
        return list != null ? new WrapperList<>(list, Prerequisites::new, Prerequisites::getDelegate) : null;
    }

}
