// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.model;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class RepositoryBase
    extends BaseObject
{

    public RepositoryBase() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.model.RepositoryBase.newInstance());
    }

    public RepositoryBase(com.netflix.tools.jig.internal.org.apache.maven.api.model.RepositoryBase delegate) {
        this(delegate, null);
    }

    public RepositoryBase(com.netflix.tools.jig.internal.org.apache.maven.api.model.RepositoryBase delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public RepositoryBase clone(){
        return new RepositoryBase(getDelegate());
    }

    public com.netflix.tools.jig.internal.org.apache.maven.api.model.RepositoryBase getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.model.RepositoryBase) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof RepositoryBase)) {
            return false;
        }
        RepositoryBase that = (RepositoryBase) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    public String getId() {
        return getDelegate().getId();
    }

    public void setId(String id) {
        if (!Objects.equals(id, getId())) {
            update(getDelegate().withId(id));
        }
    }

    public String getName() {
        return getDelegate().getName();
    }

    public void setName(String name) {
        if (!Objects.equals(name, getName())) {
            update(getDelegate().withName(name));
        }
    }

    public String getUrl() {
        return getDelegate().getUrl();
    }

    public void setUrl(String url) {
        if (!Objects.equals(url, getUrl())) {
            update(getDelegate().withUrl(url));
        }
    }

    public String getLayout() {
        return getDelegate().getLayout();
    }

    public void setLayout(String layout) {
        if (!Objects.equals(layout, getLayout())) {
            update(getDelegate().withLayout(layout));
        }
    }

    public InputLocation getLocation(Object key) {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getLocation(key);
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setLocation(Object key, InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.RepositoryBase.newBuilder(getDelegate(), true)
                        .location(key, location != null ? location.toApiLocation() : null).build());
    }

    public InputLocation getImportedFrom() {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getImportedFrom();
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setImportedFrom(InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.RepositoryBase.newBuilder(getDelegate(), true)
                        .importedFrom(location != null ? location.toApiLocation() : null).build());
    }

    public Set<Object> getLocationKeys() {
        return getDelegate().getLocationKeys();
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.model.RepositoryBase> repositoryBaseToApiV4(List<RepositoryBase> list) {
        return list != null ? new WrapperList<>(list, RepositoryBase::getDelegate, RepositoryBase::new) : null;
    }

    public static List<RepositoryBase> repositoryBaseToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.model.RepositoryBase> list) {
        return list != null ? new WrapperList<>(list, RepositoryBase::new, RepositoryBase::getDelegate) : null;
    }

}
