// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.model;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class Reporting
    extends BaseObject
{

    public Reporting() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.model.Reporting.newInstance());
    }

    public Reporting(com.netflix.tools.jig.internal.org.apache.maven.api.model.Reporting delegate) {
        this(delegate, null);
    }

    public Reporting(com.netflix.tools.jig.internal.org.apache.maven.api.model.Reporting delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public Reporting clone(){
        return new Reporting(getDelegate());
    }

    public com.netflix.tools.jig.internal.org.apache.maven.api.model.Reporting getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.model.Reporting) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof Reporting)) {
            return false;
        }
        Reporting that = (Reporting) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    public String getExcludeDefaults() {
        return getDelegate().getExcludeDefaults();
    }

    public void setExcludeDefaults(String excludeDefaults) {
        if (!Objects.equals(excludeDefaults, getExcludeDefaults())) {
            update(getDelegate().withExcludeDefaults(excludeDefaults));
        }
    }

    public String getOutputDirectory() {
        return getDelegate().getOutputDirectory();
    }

    public void setOutputDirectory(String outputDirectory) {
        if (!Objects.equals(outputDirectory, getOutputDirectory())) {
            update(getDelegate().withOutputDirectory(outputDirectory));
        }
    }

    @Nonnull
    public List<ReportPlugin> getPlugins() {
        return new WrapperList<ReportPlugin, com.netflix.tools.jig.internal.org.apache.maven.api.model.ReportPlugin>(
                    () -> getDelegate().getPlugins(), l -> update(getDelegate().withPlugins(l)),
                    d -> new ReportPlugin(d, this), ReportPlugin::getDelegate);
    }

    public void setPlugins(List<ReportPlugin> plugins) {
        if (plugins == null) {
            plugins = Collections.emptyList();
        }
        if (!Objects.equals(plugins, getPlugins())) {
            update(getDelegate().withPlugins(
                plugins.stream().map(c -> c.getDelegate()).collect(Collectors.toList())));
            plugins.forEach(e -> e.childrenTracking = this::replace);
        }
    }

    public void addPlugin(ReportPlugin plugin) {
        update(getDelegate().withPlugins(
               Stream.concat(getDelegate().getPlugins().stream(), Stream.of(plugin.getDelegate()))
                        .collect(Collectors.toList())));
        plugin.childrenTracking = this::replace;
    }

    public void removePlugin(ReportPlugin plugin) {
        update(getDelegate().withPlugins(
               getDelegate().getPlugins().stream()
                        .filter(e -> !Objects.equals(e, plugin))
                        .collect(Collectors.toList())));
        plugin.childrenTracking = null;
    }

    public InputLocation getLocation(Object key) {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getLocation(key);
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setLocation(Object key, InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.Reporting.newBuilder(getDelegate(), true)
                        .location(key, location != null ? location.toApiLocation() : null).build());
    }

    public InputLocation getImportedFrom() {
        com.netflix.tools.jig.internal.org.apache.maven.api.model.InputLocation loc = getDelegate().getImportedFrom();
        return loc != null ? new InputLocation(loc) : null;
    }

    public void setImportedFrom(InputLocation location) {
        update(com.netflix.tools.jig.internal.org.apache.maven.api.model.Reporting.newBuilder(getDelegate(), true)
                        .importedFrom(location != null ? location.toApiLocation() : null).build());
    }

    public Set<Object> getLocationKeys() {
        return getDelegate().getLocationKeys();
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        if (getDelegate().getPlugins().contains(oldDelegate)) {
            List<com.netflix.tools.jig.internal.org.apache.maven.api.model.ReportPlugin> list = new ArrayList<>(getDelegate().getPlugins());
            list.replaceAll(d -> d == oldDelegate ? (com.netflix.tools.jig.internal.org.apache.maven.api.model.ReportPlugin) newDelegate : d);
            update(getDelegate().withPlugins(list));
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.model.Reporting> reportingToApiV4(List<Reporting> list) {
        return list != null ? new WrapperList<>(list, Reporting::getDelegate, Reporting::new) : null;
    }

    public static List<Reporting> reportingToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.model.Reporting> list) {
        return list != null ? new WrapperList<>(list, Reporting::new, Reporting::getDelegate) : null;
    }



    public boolean isExcludeDefaults() {
        return (getExcludeDefaults() != null) ? Boolean.parseBoolean(getExcludeDefaults()) : false;
    }





    public void setExcludeDefaults(boolean excludeDefaults) {
        setExcludeDefaults(String.valueOf(excludeDefaults));
    }

    /**
     * Reset the <code>reportPluginMap</code> field to <code>null</code>
     */
    @Deprecated
    public void flushReportPluginMap() {
    }

    /**
     * @return a Map of plugins field with <code>ReportPlugin#getKey()</code> as key
     * @see com.netflix.tools.jig.internal.org.apache.maven.model.ReportPlugin#getKey()
     */
    public java.util.Map<String, ReportPlugin> getReportPluginsAsMap() {
        return getPlugins().stream().collect(Collectors.toMap(report -> report.getKey(), report -> report));
    }


}
