// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.artifact.repository.metadata;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class SnapshotVersion
    extends BaseObject
{

    public SnapshotVersion() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.metadata.SnapshotVersion.newInstance());
    }

    public SnapshotVersion(com.netflix.tools.jig.internal.org.apache.maven.api.metadata.SnapshotVersion delegate) {
        this(delegate, null);
    }

    public SnapshotVersion(com.netflix.tools.jig.internal.org.apache.maven.api.metadata.SnapshotVersion delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public SnapshotVersion clone(){
        return new SnapshotVersion(getDelegate());
    }

    public com.netflix.tools.jig.internal.org.apache.maven.api.metadata.SnapshotVersion getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.metadata.SnapshotVersion) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof SnapshotVersion)) {
            return false;
        }
        SnapshotVersion that = (SnapshotVersion) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    public String getClassifier() {
        return getDelegate().getClassifier();
    }

    public void setClassifier(String classifier) {
        if (!Objects.equals(classifier, getClassifier())) {
            update(getDelegate().withClassifier(classifier));
        }
    }

    public String getExtension() {
        return getDelegate().getExtension();
    }

    public void setExtension(String extension) {
        if (!Objects.equals(extension, getExtension())) {
            update(getDelegate().withExtension(extension));
        }
    }

    public String getVersion() {
        return getDelegate().getVersion();
    }

    public void setVersion(String version) {
        if (!Objects.equals(version, getVersion())) {
            update(getDelegate().withVersion(version));
        }
    }

    public String getUpdated() {
        return getDelegate().getUpdated();
    }

    public void setUpdated(String updated) {
        if (!Objects.equals(updated, getUpdated())) {
            update(getDelegate().withUpdated(updated));
        }
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.metadata.SnapshotVersion> snapshotVersionToApiV4(List<SnapshotVersion> list) {
        return list != null ? new WrapperList<>(list, SnapshotVersion::getDelegate, SnapshotVersion::new) : null;
    }

    public static List<SnapshotVersion> snapshotVersionToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.metadata.SnapshotVersion> list) {
        return list != null ? new WrapperList<>(list, SnapshotVersion::new, SnapshotVersion::getDelegate) : null;
    }

}
