// =================== DO NOT EDIT THIS FILE ====================
//  Generated by Modello Velocity from model-v3.vm
//  template, any modifications will be overwritten.
// ==============================================================
package com.netflix.tools.jig.internal.org.apache.maven.artifact.repository.metadata;

import java.io.Serializable;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Generated;
import com.netflix.tools.jig.internal.org.apache.maven.api.annotations.Nonnull;

@Generated
public class Versioning
    extends BaseObject
{

    public Versioning() {
        this(com.netflix.tools.jig.internal.org.apache.maven.api.metadata.Versioning.newInstance());
    }

    public Versioning(com.netflix.tools.jig.internal.org.apache.maven.api.metadata.Versioning delegate) {
        this(delegate, null);
    }

    public Versioning(com.netflix.tools.jig.internal.org.apache.maven.api.metadata.Versioning delegate, BaseObject parent) {
        super(delegate, parent);
    }

    public Versioning clone(){
        return new Versioning(getDelegate());
    }

    public com.netflix.tools.jig.internal.org.apache.maven.api.metadata.Versioning getDelegate() {
        return (com.netflix.tools.jig.internal.org.apache.maven.api.metadata.Versioning) super.getDelegate();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || !(o instanceof Versioning)) {
            return false;
        }
        Versioning that = (Versioning) o;
        return Objects.equals(this.delegate, that.delegate);
    }

    @Override
    public int hashCode() {
        return getDelegate().hashCode();
    }

    public String getLatest() {
        return getDelegate().getLatest();
    }

    public void setLatest(String latest) {
        if (!Objects.equals(latest, getLatest())) {
            update(getDelegate().withLatest(latest));
        }
    }

    public String getRelease() {
        return getDelegate().getRelease();
    }

    public void setRelease(String release) {
        if (!Objects.equals(release, getRelease())) {
            update(getDelegate().withRelease(release));
        }
    }

    @Nonnull
    public List<String> getVersions() {
        return new WrapperList<String, String>(() -> getDelegate().getVersions(), this::setVersions, s -> s, s -> s);
    }

    public void setVersions(List<String> versions) {
        if (!Objects.equals(versions, getVersions())) {
            update(getDelegate().withVersions(versions));
        }
    }

    public void addVersion(String version) {
        update(getDelegate().withVersions(
               Stream.concat(getDelegate().getVersions().stream(), Stream.of(version))
                        .collect(Collectors.toList())));
    }

    public void removeVersion(String version) {
        update(getDelegate().withVersions(
               getDelegate().getVersions().stream()
                        .filter(e -> !Objects.equals(e, version))
                        .collect(Collectors.toList())));
    }

    public String getLastUpdated() {
        return getDelegate().getLastUpdated();
    }

    public void setLastUpdated(String lastUpdated) {
        if (!Objects.equals(lastUpdated, getLastUpdated())) {
            update(getDelegate().withLastUpdated(lastUpdated));
        }
    }

    public Snapshot getSnapshot() {
        return getDelegate().getSnapshot() != null ? new Snapshot(getDelegate().getSnapshot(), this) : null;
    }

    public void setSnapshot(Snapshot snapshot) {
        if (!Objects.equals(snapshot, getSnapshot())){
            if (snapshot != null) {
                update(getDelegate().withSnapshot(snapshot.getDelegate()));
                snapshot.childrenTracking = this::replace;
            } else {
                update(getDelegate().withSnapshot(null));
            }
        }
    }

    @Nonnull
    public List<SnapshotVersion> getSnapshotVersions() {
        return new WrapperList<SnapshotVersion, com.netflix.tools.jig.internal.org.apache.maven.api.metadata.SnapshotVersion>(
                    () -> getDelegate().getSnapshotVersions(), l -> update(getDelegate().withSnapshotVersions(l)),
                    d -> new SnapshotVersion(d, this), SnapshotVersion::getDelegate);
    }

    public void setSnapshotVersions(List<SnapshotVersion> snapshotVersions) {
        if (snapshotVersions == null) {
            snapshotVersions = Collections.emptyList();
        }
        if (!Objects.equals(snapshotVersions, getSnapshotVersions())) {
            update(getDelegate().withSnapshotVersions(
                snapshotVersions.stream().map(c -> c.getDelegate()).collect(Collectors.toList())));
            snapshotVersions.forEach(e -> e.childrenTracking = this::replace);
        }
    }

    public void addSnapshotVersion(SnapshotVersion snapshotVersion) {
        update(getDelegate().withSnapshotVersions(
               Stream.concat(getDelegate().getSnapshotVersions().stream(), Stream.of(snapshotVersion.getDelegate()))
                        .collect(Collectors.toList())));
        snapshotVersion.childrenTracking = this::replace;
    }

    public void removeSnapshotVersion(SnapshotVersion snapshotVersion) {
        update(getDelegate().withSnapshotVersions(
               getDelegate().getSnapshotVersions().stream()
                        .filter(e -> !Objects.equals(e, snapshotVersion))
                        .collect(Collectors.toList())));
        snapshotVersion.childrenTracking = null;
    }

    protected boolean replace(Object oldDelegate, Object newDelegate) {
        if (super.replace(oldDelegate, newDelegate)) {
            return true;
        }
        if (oldDelegate == getDelegate().getSnapshot()) {
            update(getDelegate().withSnapshot((com.netflix.tools.jig.internal.org.apache.maven.api.metadata.Snapshot) newDelegate));
            return true;
        }
        if (getDelegate().getSnapshotVersions().contains(oldDelegate)) {
            List<com.netflix.tools.jig.internal.org.apache.maven.api.metadata.SnapshotVersion> list = new ArrayList<>(getDelegate().getSnapshotVersions());
            list.replaceAll(d -> d == oldDelegate ? (com.netflix.tools.jig.internal.org.apache.maven.api.metadata.SnapshotVersion) newDelegate : d);
            update(getDelegate().withSnapshotVersions(list));
            return true;
        }
        return false;
    }

    public static List<com.netflix.tools.jig.internal.org.apache.maven.api.metadata.Versioning> versioningToApiV4(List<Versioning> list) {
        return list != null ? new WrapperList<>(list, Versioning::getDelegate, Versioning::new) : null;
    }

    public static List<Versioning> versioningToApiV3(List<com.netflix.tools.jig.internal.org.apache.maven.api.metadata.Versioning> list) {
        return list != null ? new WrapperList<>(list, Versioning::new, Versioning::getDelegate) : null;
    }


    public void updateTimestamp()
    {
        setLastUpdatedTimestamp( new java.util.Date() );
    }

    public void setLastUpdatedTimestamp( java.util.Date date )
    {
        java.util.TimeZone timezone = java.util.TimeZone.getTimeZone( "UTC" );
        java.text.DateFormat fmt = new java.text.SimpleDateFormat( "yyyyMMddHHmmss" );
        fmt.setTimeZone( timezone );
        setLastUpdated( fmt.format( date ) );
    }

}
